# Generated by Django 2.1.3 on 2018-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('text', models.CharField(max_length=1024)),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
